### ISSUE TITLE
A lot of restarts of the report service, because JDBC connection timeout, because we have a lot of threads

### ISSUE THREAD

**Issue by polarnik** [qameta/allure-testops-deployment#102]
Hello!

Default thread pool settings are not the best:
```yaml
report:
  replicaCount: 1
  cache:
    enabled: false
    ttlByDefault: 1m
    ttlWidgetsAutomationTrend: 1h
    ttlWidgetsProjectMetricTrend: 1h
    ttlWidgetsLaunchDurationHistogram: 1h
    ttlWidgetsAnalyticPieChart: 1h
    ttlWidgetsTrComplexTrend: 1h
    ttlWidgetsTrStatisticTrend: 1h
    ttlWidgetsTcLastResult: 1h
  image: allure-report
  maxDBConn: 10
  maxConcurrency: 5
  maxS3Concurrency: 200
  taskExecutorCorePoolSize: 200
```
The source:
https://github.com/qameta/allure-testops-deployment/blob/master/charts/allure-testops/values.yaml

200 threads rabbitConnectionFactorySharedExecutor (taskExecutorCorePoolSize: 200) can not work with 10 JDBC connections (maxDBConn: 10), only. Allure health check will not get a free connection, and Kubernetes will restart the service, because the service is not healthy.

And 200 threads rabbitConnectionFactorySharedExecutor will allocate all CPU resources in PostgreSQL.

The best settings are:

```yaml
  maxDBConn: 50
  maxConcurrency: 5
  taskExecutorCorePoolSize: 10
```

**Comment by polarnik** [comment]
For example, we have many taskExecutorCorePoolSize (rabbitConnectionFactorySharedExecutor)

![image](https://github.com/user-attachments/assets/49cbcc80-4085-4a6b-a001-6bd2e9289091)

We will have 100% CPU Usage in PostgreSQL and the service restarts:

![image](https://github.com/user-attachments/assets/740f5390-eaa2-4137-b150-f21bd7d333f7)
![image](https://github.com/user-attachments/assets/42f1ba8a-3293-4e24-b3fa-15da59eca311)

Take a look on the day: 08/15

The config was updated on 08/19:
```yaml
  maxDBConn: 50
  maxConcurrency: 5
  taskExecutorCorePoolSize: 10
```

The service is working well, without restarts amd without 100% CPU Usage in PostgreSQL
