### ISSUE TITLE
QP800 🆙 to add support for different db servers for uaa and report databases

### ISSUE THREAD

**Issue by Hermit91** [qameta/allure-testops-deployment#12]
Request question:
"We have 2 external database servers: UAA and Report. In the new helm chart, there is only 1 place to enter external endpoint. Can you provide guidance to use 2 external database servers?"

currently the end user has the following implementation using old helm chart:

```yaml
uaa:
  env:
    open:
      # database
      SPRING_DATASOURCE_URL: "jdbc:postgresql://**${UAA_DATABASE_URL}**/${UAA_DATABASE_NAME}"
      ALLURE_ENDPOINT: "https://${HOST_URL}"
    secret:
      SPRING_DATASOURCE_USERNAME: uaa 
      SPRING_DATASOURCE_PASSWORD: "${UAA_DATABASE_PASSWORD}"
      ALLURE_CRYPTO_PASSWORD: "${CRYPTO_PASSWORD}"
      ALLURE_REGISTRATION_ENABLED: "false"

report:
  persistence:
    size: ${PVC_SIZE}
  env:
    open:
      # database
      SPRING_DATASOURCE_URL: "jdbc:postgresql://**${REPORT_DATABASE_URL}**/${REPORT_DATABASE_NAME}"
      ALLURE_ENDPOINT: "https://${HOST_URL}"
      ALLURE_BLOBSTORAGE_TYPE: "S3"
      ALLURE_BLOBSTORAGE_S3_ENDPOINT: "s3.amazonaws.com" #leave as it is
      ALLURE_BLOBSTORAGE_S3_REGION: "${AWS_REGION}" # region, update accordingly your real region
      ALLURE_BLOBSTORAGE_S3_BUCKET: "${S3_BUCKET_NAME}" # replace string in <> with your bucket's name 
    secret:
      SPRING_DATASOURCE_USERNAME: report
      SPRING_DATASOURCE_PASSWORD: "${REPORT_DATABASE_PASSWORD}"
      ALLURE_CRYPTO_PASSWORD: "${CRYPTO_PASSWORD}"
```
i.e. 2 different database servers are used

- {REPORT_DATABASE_URL}
- {UAA_DATABASE_URL}

we need to support such scheme as well in this very helm chart to allow tansparent update to this chart from the old one
