### ISSUE TITLE
Enable SSL for RabbitMQ in the report statefulset

### ISSUE THREAD

**Issue by tdahlin** [qameta/allure-testops-deployment#23]
When using an external RabbitMQ server, in AWS in particular, I need to enable SSL. this can be achieved by setting the environment variable `SPRING_RABBITMQ_SSL_ENABLED` in the  report statefulset

```yaml
    spec:
      containers:
        - env:
          - name: SPRING_RABBITMQ_SSL_ENABLED
            value: "true"
```
