### ISSUE TITLE
ErrImagePull with helm deploy for 4.16.4

### ISSUE THREAD

**Issue by ialshaev** [qameta/allure-testops-deployment#39]
Hey,

facing the following issue when deploying allure with helm on k8s:
`allure-testops-gateway-747cdd6cc5-6j6zs   0/1     ErrImagePull       0               16m`

The `docker login` on worker nodes is not the reason here cause I made sure to login with credentials that sales have been provided me with.

The only thing that allows us to fix such behaviour is to manually pull gateway, uaa and report images on all nodes - and this is ugly.

p.s. If I forgot to mention any important note - let me know.

**Comment by a-ryoo** [comment]
Hi, could you plz attach your values.yaml with secrets redacted

**Comment by vvp1983** [comment]
Error because no secret config create while deploy helm. No .Values.registry.auth use in helm chart template. Only .Values.registry.imagePullSecret. So need manual create kubectl create secret docker-registry registry-allure and use it in helm chart.  
`grep 'registry' -rn ./
./charts/allure-testops/templates/_helpers.tpl:4:{{- with .Values.registry }}
./charts/allure-testops/templates/allure/gateway-dep.yaml:36:        - name: {{ .Values.registry.imagePullSecret }}
./charts/allure-testops/templates/allure/gateway-dep.yaml:49:          image: "{{ .Values.registry.repo }}/{{ .Values.registry.name }}/{{ .Values.gateway.image }}:{{ .Values.version | default .Chart.AppVersion }}"
./charts/allure-testops/templates/allure/gateway-dep.yaml:50:          imagePullPolicy: {{ .Values.registry.pullPolicy }}
./charts/allure-testops/templates/allure/report-statefulset.yaml:36:        - name: {{ .Values.registry.imagePullSecret }}
./charts/allure-testops/templates/allure/report-statefulset.yaml:61:          image: "{{ .Values.registry.repo }}/{{ .Values.registry.name }}/{{ .Values.capacitor.image }}:{{ .Values.capacitor.version | default "latest" }}"
./charts/allure-testops/templates/allure/report-statefulset.yaml:62:          imagePullPolicy: {{ .Values.registry.pullPolicy }}
./charts/allure-testops/templates/allure/report-statefulset.yaml:109:          image: "{{ .Values.registry.repo }}/{{ .Values.registry.name }}/{{ .Values.report.image }}:{{ .Values.version | default .Chart.AppVersion }}"
./charts/allure-testops/templates/allure/report-statefulset.yaml:110:          imagePullPolicy: {{ .Values.registry.pullPolicy }}
./charts/allure-testops/templates/allure/uaa-dep.yaml:35:        - name: {{ .Values.registry.imagePullSecret }}
./charts/allure-testops/templates/allure/uaa-dep.yaml:58:          image: "{{ .Values.registry.repo }}/{{ .Values.registry.name }}/{{ .Values.uaa.image }}:{{ .Values.version | default .Chart.AppVersion }}"
./charts/allure-testops/templates/allure/uaa-dep.yaml:59:          imagePullPolicy: {{ .Values.registry.pullPolicy }}
./charts/allure-testops/templates/infra/keydb.yaml:36:          imagePullPolicy: {{ .Values.registry.pullPolicy }}
./charts/allure-testops/templates/infra/regcred-secret.yaml:1:{{- if .Values.registry.enabled }}
./charts/allure-testops/templates/infra/regcred-secret.yaml:6:  name: {{ .Values.registry.imagePullSecret }}
./charts/allure-testops/values.yaml:32:## Registry Auth. Access to registry secrets can be obtained from QAMeta team
./charts/allure-testops/values.yaml:33:registry:
./charts/allure-testops/values.yaml:34:  # Private registry or Proxy like Nexus
./charts/allure-testops/values.yaml:37:  # registry to pull images from
./charts/allure-testops/values.yaml:40:  # Prefix with registry name
./charts/allure-testops/values.yaml:42:  # name (label) of registry secret
./charts/allure-testops/values.yaml:206:    # If you have private registry it should look like reg.domain.tld/postgres:14
`
If deploy helm chart got unknown: repository docker.io/allure/allure-gateway not found. But manual login in docker.io with token  - successfull.

**Comment by a-ryoo** [comment]
Wait a bit.
Please look at values.yaml:
```yaml
## Registry Auth. Access to registry secrets can be obtained from QAMeta team
registry:
  # Private registry or Proxy like Nexus
  enabled: false
  # Registry Domain like quay.io / docker.io / ghcr.io / ...
  # registry to pull images from
  # default is docker.io
  repo: docker.io
  # Prefix with registry name
  name: allure
  # name (label) of registry secret
  imagePullSecret: qameta-secret
  pullPolicy: IfNotPresent
  auth:
    # provided by Qameta Software
    # by default qametaaccess as username and a password (token) provided by sales
    username: qametaaccess
    password: <GetFrom sales at qameta.io>
```
Registry Credentials Secret gets created when 
```yaml
registry:
  enabled: true
```
Our main images registry is located at dl.qameta.io and you should obtain username and pass from qameta to proceed.
You still can proceed with docker credentials if you have them. registry.enabled=false by default because we leave customers an option to use existing registry secret if they have reason to do so
