### ISSUE TITLE
Okta clientsecret doesn't get rendered in k8s template

### ISSUE THREAD

**Issue by jfengupgrade** [qameta/allure-testops-deployment#46]
hello,

While we implement the okta with allure-testops, we found the env `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENTSECRET`  is not get rendered in k8s template.

Based on https://docs.qameta.io/allure-testops/getstarted/auth/openid-okta/#configuring-allure-testops
we need put the value as 
```
gateway:
  env:
    open:
      <snip>
    secret:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENTSECRET: <Client secret>
```
it is not handled by the template
https://github.com/qameta/allure-testops-deployment/blob/master/charts/allure-testops/templates/allure/gateway-dep.yaml#L149-L152
it works until we put the secret key as `gateway.env.open.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENTSECRET`
but in that way we will show the secret as plain test in the manifest

Could you help update it to the same logic as `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENTSECRET`?

Thanks,
