### ISSUE TITLE
Upgrade usability of secrets

### ISSUE THREAD

**Issue by purisev** [qameta/allure-testops-deployment#96]
Dependent services will broke if you change default passwords in values.yaml
It can be improved by using the secret created in chart.

Also you need to allow using existed secret for pulling image.

**Comment by purisev** [comment]
I suggest to:

1) add in values.yaml:
```
registry:
  # User already existing secret for pulling image
  useExistedSecret: false

defaultSecret:
  name: "allure-testops-secret"
  
redis:
  auth:
    # Use existing Secret
    existingSecret: "allure-testops-secret"
    
rabbitmq:
  auth:
    existingPasswordSecret: "allure-testops-secret"  
```

2) change in templates\_helpers.tpl define of imagePullSecret to:
```
{{- define "imagePullSecret" }}
  {{- if not .Values.registry.useExistedSecret }}
  {{- with .Values.registry }}
    {{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .repo .auth.username .auth.password (printf "%s:%s" .auth.username .auth.password | b64enc) | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
```

3) change in templates\infra\secret.yaml:
```
metadata:
  name: {{ .Values.defaultSecret.name }}
```
4) and in templates\infra\secret.yaml:
```
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.auth.erlangCookie | b64enc | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
```
